### ISSUE TITLE
Campaign Manager Code

### ISSUE THREAD

**Issue by Olyve** [joerez/MERN-SPA-Starter#1]
Hey Joe, I was reading through the code and there are some sections in `App.js` that are copied from your project. You might want to remove the Campaign Manager specifics and make it more generalized. There also seem to be some code for sending texts? That probably isn't necessary for a template! Starter looks great other wise!

**Comment by joerez** [comment]
Thanks Sam, I will go through and get rid of those. They were leftover from one of my projects I used as a template for this.
